In [1]:
!pip install tensorflow==2.0.0-rc1

     |████████████████████████████████| 86.3MB 35.8MB/s 
     |████████████████████████████████| 4.3MB 31.2MB/s 
     |████████████████████████████████| 501kB 43.6MB/s 
  Found existing installation: tensorflow 1.14.0
    Uninstalling tensorflow-1.14.0:
      Successfully uninstalled tensorflow-1.14.0


In [4]:
import tensorflow as tf

import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.0.0-rc1


In [0]:
# Build the dataset from np.array()
my_data = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 13, 45, 66, 77, 12, 44, 52, 12, 12, 23, 13, 14, 15, 17]))

In [103]:
# Generate shifts
my_data = my_data.window(10, shift = 1)

for window in my_data:
    for val in window:
        print(val.numpy(), end = ' ')
    print()


1 2 13 45 66 77 12 44 52 12 
2 13 45 66 77 12 44 52 12 12 
13 45 66 77 12 44 52 12 12 23 
45 66 77 12 44 52 12 12 23 13 
66 77 12 44 52 12 12 23 13 14 
77 12 44 52 12 12 23 13 14 15 
12 44 52 12 12 23 13 14 15 17 
44 52 12 12 23 13 14 15 17 
52 12 12 23 13 14 15 17 
12 12 23 13 14 15 17 
12 23 13 14 15 17 
23 13 14 15 17 
13 14 15 17 
14 15 17 
15 17 
17 


In [105]:
# Generate shifts and drop remainder
my_data = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 13, 45, 66, 77, 12, 44, 52, 12, 12, 23, 13, 14, 15, 17]))

my_data = my_data.window(10, shift = 1, drop_remainder = True)

for window in my_data:
    for val in window:
        print(val.numpy(), end = ' ')
    print()


1 2 13 45 66 77 12 44 52 12 
2 13 45 66 77 12 44 52 12 12 
13 45 66 77 12 44 52 12 12 23 
45 66 77 12 44 52 12 12 23 13 
66 77 12 44 52 12 12 23 13 14 
77 12 44 52 12 12 23 13 14 15 
12 44 52 12 12 23 13 14 15 17 


In [106]:
# Create rows
my_data = my_data.flat_map(lambda window: window.batch(10))

for i in my_data:
    print(i.numpy())

[ 1  2 13 45 66 77 12 44 52 12]
[ 2 13 45 66 77 12 44 52 12 12]
[13 45 66 77 12 44 52 12 12 23]
[45 66 77 12 44 52 12 12 23 13]
[66 77 12 44 52 12 12 23 13 14]
[77 12 44 52 12 12 23 13 14 15]
[12 44 52 12 12 23 13 14 15 17]


In [108]:
# Split to xs and ys
my_data = my_data.map(lambda window: (window[:-1], window[-1:]))

for x, y in my_data:
  print(x.numpy(), y.numpy())

[ 1  2 13 45 66 77 12 44 52] [12]
[ 2 13 45 66 77 12 44 52 12] [12]
[13 45 66 77 12 44 52 12 12] [23]
[45 66 77 12 44 52 12 12 23] [13]
[66 77 12 44 52 12 12 23 13] [14]
[77 12 44 52 12 12 23 13 14] [15]
[12 44 52 12 12 23 13 14 15] [17]


In [111]:
# Shuffle the data
my_data = my_data.shuffle(buffer_size = 10)

for x, y in my_data:
  print(x.numpy(), y.numpy())

[13 45 66 77 12 44 52 12 12] [23]
[77 12 44 52 12 12 23 13 14] [15]
[12 44 52 12 12 23 13 14 15] [17]
[66 77 12 44 52 12 12 23 13] [14]
[ 1  2 13 45 66 77 12 44 52] [12]
[ 2 13 45 66 77 12 44 52 12] [12]
[45 66 77 12 44 52 12 12 23] [13]


In [112]:
# Create batches (and use `prefetch` to optimize performance)
my_data = my_data.batch(2).prefetch(1)

for x, y in my_data:
  print("x:\n", x.numpy())
  print("y:\n", y.numpy())
  print('\n')

x:
 [[ 2 13 45 66 77 12 44 52 12]
 [77 12 44 52 12 12 23 13 14]]
y:
 [[12]
 [15]]


x:
 [[ 1  2 13 45 66 77 12 44 52]
 [13 45 66 77 12 44 52 12 12]]
y:
 [[12]
 [23]]


x:
 [[12 44 52 12 12 23 13 14 15]
 [66 77 12 44 52 12 12 23 13]]
y:
 [[17]
 [14]]


x:
 [[45 66 77 12 44 52 12 12 23]]
y:
 [[13]]


